apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mychart.pvc" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}